#!/bin/sh
set -eu

. "$HOME/.local/env.shell"

cd -- "$(dirname -- "$0")"

if [ -d "bootstrap.d" ]
then
    find -L "bootstrap.d" -type f | sort | while IFS="
" read -r script
    do
        if [ -x "$script" ] && echo "$script" | grep -qv "##"
        then
            echo "[X] Executing '$script'..."
            if ! "$script" bootstrap
            then
                echo "Error: '$script' failed, aborting bootstrap"
                exit 1
            fi
        fi
    done
fi

