#!/bin/sh
set -eu

cd -- "$(dirname -- "$0")"
[ -d "bootstrap.d" ] || exit 0

. "${XDG_CONFIG_HOME:-"$HOME/.config"}/xdg_paths.shell"

find -L "bootstrap.d" -type f | sort | while IFS="
" read -r script
do
    if [ -x "$script" ] && echo "$script" | grep -qv "##"
    then
        echo "[X] Executing '$script'..." >&2
        if ! "$script" >&2
        then
            echo "Error: '$script' failed, aborting bootstrap" >&2
            exit 1
        fi
    fi
done

