#!/bin/sh
set -eu

case "$1" in
    bootstrap)
        echo

        echo "Downloading gdb-dashboard..."
        if ! curl -fLo "$XDG_CONFIG_HOME/gdb/dashboard" --create-dirs \
            "https://raw.githubusercontent.com/cyrus-and/gdb-dashboard/master/.gdbinit"
        then
            echo "Couldn't download gdb-dashboard"
            exit 1
        fi

        echo
        ;;

    cleanup)
        echo

        echo "Removing gdb-dashboard..."
        rm -- "$XDG_CONFIG_HOME/gdb/dashboard"

        echo
        ;;
esac

