#!/bin/sh
set -eu

case "$1" in
    bootstrap)
        echo

        echo "Downloading prompt.py..."
        if ! curl -fLo "$USER_BINARIES_PATH/prompt.py" --create-dirs \
            "https://raw.githubusercontent.com/ivanp7/prompt/master/prompt.py"
        then
            echo "Couldn't download prompt.py"
            exit 1
        fi

        echo "Downloading prompt.sh..."
        if ! curl -fLo "$USER_BINARIES_PATH/prompt.sh" --create-dirs \
            "https://raw.githubusercontent.com/ivanp7/prompt/master/prompt.sh"
        then
            echo "Couldn't download prompt.sh"
            exit 1
        fi

        echo "Setting permissions for prompt.py and prompt.sh..."
        chmod +x "$USER_BINARIES_PATH/prompt.py" "$USER_BINARIES_PATH/prompt.sh"

        echo
        ;;

    cleanup)
        echo

        echo "Removing prompt.py and prompt.sh..."
        rm -- "$USER_BINARIES_PATH/prompt.py" "$USER_BINARIES_PATH/prompt.sh"

        echo
        ;;
esac

