#!/bin/sh
set -eu

case "$1" in
    bootstrap)
        echo

        echo "Downloading vim-plug..."
        if ! curl -fLo "$XDG_DATA_HOME/nvim/site/autoload/plug.vim" --create-dirs \
            "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        then
            echo "Couldn't download vim-plug"
            exit 1
        fi
        echo

        if [ ! -d "$XDG_CACHE_HOME/nvim/plugged" ]
        then
            echo "Invoking :PlugInstall command..."
            nvim -es -u "$XDG_CONFIG_HOME/nvim/init.vim" -i NONE -c "PlugInstall" -c "qa"
        else
            echo "Invoking :PlugUpdate command..."
            nvim -es -u "$XDG_CONFIG_HOME/nvim/init.vim" -i NONE -c "PlugUpdate" -c "qa"

            echo "Invoking :PlugClean! command..."
            nvim -es -u "$XDG_CONFIG_HOME/nvim/init.vim" -i NONE -c "PlugClean!" -c "qa"
        fi

        if [ ! -d "$XDG_DATA_HOME/nvim/backup" ]
        then
            echo "Creating backup directory..."
            mkdir -p -- "$XDG_DATA_HOME/nvim/backup"
        fi

        echo
        ;;

    cleanup)
        echo

        echo "Remove vim-plug..."
        rm -- "$XDG_DATA_HOME/nvim/site/autoload/plug.vim"
        rmdir -p --ignore-fail-on-non-empty -- "$XDG_DATA_HOME/nvim/site/autoload"

        echo "Remove vim plugins directory..."
        rm -rf -- "$XDG_CACHE_HOME/nvim/plugged"

        echo
        ;;
esac

