#!/bin/sh
set -eu

case "$1" in
    bootstrap)
        echo

        echo "Downloading remote.py..."
        if ! curl -fLo "$USER_BINARIES_PATH/remote.py" --create-dirs \
            "https://raw.githubusercontent.com/ivanp7/remote-control/python/remote.py"
        then
            echo "Couldn't download remote.py"
            exit 1
        fi

        echo "Setting permissions for remote.py..."
        chmod +x "$USER_BINARIES_PATH/remote.py"

        echo
        ;;

    cleanup)
        echo

        echo "Removing remote.py..."
        rm -- "$USER_BINARIES_PATH/remote.py"

        echo
        ;;
esac

