#! /bin/sh

. "$HOME/.local/env.shell"

#
# Bspwm configuration
#

bspc config border_width        2
bspc config window_gap          10

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      false

bspc config focus_follows_pointer false

bspc config pointer_modifier    mod4
bspc config pointer_action1     move
bspc config pointer_action2     resize_side
bspc config pointer_action3     resize_corner

bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/rules"

#
# Autostart
#

# asynchronous
[ ! -d "$XDG_CONFIG_HOME/bspwm/autostart.d" ] ||
find "$XDG_CONFIG_HOME/bspwm/autostart.d" -type f | sort | while IFS="
" read -r script
do
    [ ! -x "$script" ] || "$script" &
done

# synchronous
[ ! -d "$XDG_CONFIG_HOME/bspwm/autostart_sync.d" ] ||
find "$XDG_CONFIG_HOME/bspwm/autostart_sync.d" -type f | sort | while IFS="
" read -r script
do
    [ ! -x "$script" ] || "$script"
done

