#!/bin/sh

export RECTANGLE="${SCRATCHPAD2_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD2_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD2_HEIGHT:-}"
    export X="${SCRATCHPAD2_X:-}"
    export Y="${SCRATCHPAD2_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

