#!/bin/sh

export RECTANGLE="${SCRATCHPAD8_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD8_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD8_HEIGHT:-}"
    export X="${SCRATCHPAD8_X:-}"
    export Y="${SCRATCHPAD8_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

