#!/bin/sh

export RECTANGLE="${SCRATCHPAD4_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD4_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD4_HEIGHT:-}"
    export X="${SCRATCHPAD4_X:-}"
    export Y="${SCRATCHPAD4_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

