#!/bin/sh

export RECTANGLE="${SCRATCHPAD6_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD6_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD6_HEIGHT:-}"
    export X="${SCRATCHPAD6_X:-}"
    export Y="${SCRATCHPAD6_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

