#!/bin/sh

export RECTANGLE="${SCRATCHPAD5_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD5_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD5_HEIGHT:-}"
    export X="${SCRATCHPAD5_X:-}"
    export Y="${SCRATCHPAD5_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

