#!/bin/sh

export RECTANGLE="${SCRATCHPAD11_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD11_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD11_HEIGHT:-}"
    export X="${SCRATCHPAD11_X:-}"
    export Y="${SCRATCHPAD11_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

