#!/bin/sh

export RECTANGLE="${SCRATCHPAD1_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD1_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD1_HEIGHT:-}"
    export X="${SCRATCHPAD1_X:-}"
    export Y="${SCRATCHPAD1_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

