#!/bin/sh

export RECTANGLE="${SCRATCHPAD12_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD12_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD12_HEIGHT:-}"
    export X="${SCRATCHPAD12_X:-}"
    export Y="${SCRATCHPAD12_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

