#!/bin/sh

export RECTANGLE="${SCRATCHPAD7_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD7_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD7_HEIGHT:-}"
    export X="${SCRATCHPAD7_X:-}"
    export Y="${SCRATCHPAD7_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

