#!/bin/sh

export RECTANGLE="${SCRATCHPAD3_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD3_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD3_HEIGHT:-}"
    export X="${SCRATCHPAD3_X:-}"
    export Y="${SCRATCHPAD3_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

