#!/bin/sh

export RECTANGLE="${SCRATCHPAD0_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD0_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD0_HEIGHT:-}"
    export X="${SCRATCHPAD0_X:-}"
    export Y="${SCRATCHPAD0_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

