#!/bin/sh

export RECTANGLE="${SCRATCHPAD10_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD10_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD10_HEIGHT:-}"
    export X="${SCRATCHPAD10_X:-}"
    export Y="${SCRATCHPAD10_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

