#!/bin/sh

export RECTANGLE="${SCRATCHPAD9_RECTANGLE:-}"
if [ -z "$RECTANGLE" ]
then
    export WIDTH="${SCRATCHPAD9_WIDTH:-}"
    export HEIGHT="${SCRATCHPAD9_HEIGHT:-}"
    export X="${SCRATCHPAD9_X:-}"
    export Y="${SCRATCHPAD9_Y:-}"
else
    unset WIDTH HEIGHT X Y
fi

exec "./scratchpad" "$@"

